### ISSUE TITLE
Update Instructions

### ISSUE THREAD

**Issue by since1976** [jhardy/compass-ceaser-easing#1]
Dude you might like to update your install instructions for when you are adding the plugin to an existing project.

`
# import ceaser-easing into your sass/scss file

@import "ceaser-easing"
`

Should read

`
# import ceaser-easing into your sass/scss file

@import "ceaser" 
` 
Cheers
Dan

**Comment by jhardy** [comment]
Are you having issues when using

```
@import "ceaser-easing" 
```

When installing the ceaser-easing plugin a partial, called ceaser,  is generated for you that shows how to use it and a has a reference to all the easing types. It's not designed to be imported. If you're having trouble using @import ceaser-easing let me know so I can take a look at it, and I will also update the documentation to talk about the ceaser partial.

**Comment by jhardy** [comment]
Closing for now, if you still have problems with this please re-open and let me know.
