### ISSUE TITLE
Transition Mixin: Unitless Delay Values don't work in Firefox

### ISSUE THREAD

**Issue by patocallaghan** [jhardy/compass-ceaser-easing#4]
This isn't an issue with your plugin but rather something to be aware of for Firefox devs.

If I use the ceaser-transition mixin and don't pass through a delay value e.g.

```
@include ceaser-transition(easeOutQuint, all, 500ms);
```

it generates the following CSS with a delay of `0`:
     -moz-transition: all 700ms cubic-bezier(0.250, 0.460, 0.450, 0.940) 0;

This CSS doesn't work in Firefox due to a bug where unitless delay values are ignored. See https://bugzilla.mozilla.org/show_bug.cgi?id=662171. This bug mentions `-moz-animation` but it's also relevant for `-moz-transition`

To get ceaser to work I have to pass through a delay of `0s`.

```
@include ceaser-transition(easeOutQuint, all, 500ms, 0s);
```

which generates

```
 -moz-transition: all 700ms cubic-bezier(0.250, 0.460, 0.450, 0.940) 0s;
```

I've an example fiddle here with the generated CSS http://jsfiddle.net/ssNKX/3/

**Comment by carlosrberto** [comment]
I had the same problem.
