### ISSUE TITLE
Sass 3.2.5

### ISSUE THREAD

**Issue by ai** [jhardy/compass-ceaser-easing#7]
Plugin doesn’t work with Sass 3.2.5. It write output jist like `cubic-bezier(easeInOutQuart)`.

**Comment by ai** [comment]
Sorry, I understand, that you just change API.

**Comment by jhardy** [comment]
I will make that a little more clear in the docs. Sorry for the confusion.

**Comment by ai** [comment]
OK. I update http://easings.net/ too :).

**Comment by jhardy** [comment]
This is awesome!, Will link to this in the updated docs as wel.
